title: WasteWing
author: Dominik Bartsch, Nhat Khanh Hoang, Gajus Petrauskas
theme: minima
markdown: kramdown

# navbar only for specific sites
header_pages:
  - hardware.md
  - remote-communication.md
  - autopilot.md
  - ai-app.md
  - drop.md
